/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#00354a",
        "on-primary-fixed-variant": "#304f00",
        background: "#0f1419",
        "inverse-on-surface": "#2c3136",
        tertiary: "#a1dbff",
        "on-error": "#690005",
        "surface-container-high": "#252a30",
        "surface-container": "#1b2025",
        "surface-container-highest": "#30353b",
        "on-surface-variant": "#c1cab0",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004c69",
        error: "#ffb4ab",
        "secondary-container": "#324e48",
        secondary: "#aecdc4",
        "surface-container-lowest": "#0a0f14",
        "inverse-primary": "#416900",
        "primary-fixed": "#acf847",
        "on-primary-fixed": "#102000",
        "surface-tint": "#91db2a",
        "tertiary-fixed": "#c4e7ff",
        "surface-bright": "#353a3f",
        primary: "#9ee939",
        "on-secondary": "#19352f",
        "primary-container": "#84cc16",
        "on-tertiary-container": "#004f6c",
        "on-secondary-container": "#a0bfb6",
        "outline-variant": "#424936",
        "on-background": "#dee3ea",
        "secondary-fixed": "#cae9e0",
        "surface-variant": "#30353b",
        "on-primary": "#1f3700",
        "on-secondary-fixed-variant": "#304c46",
        "surface-container-low": "#171c21",
        "secondary-fixed-dim": "#aecdc4",
        "on-surface": "#dee3ea",
        surface: "#0f1419",
        "tertiary-container": "#45c4ff",
        "on-secondary-fixed": "#02201b",
        "on-primary-container": "#315200",
        outline: "#8b947d",
        "tertiary-fixed-dim": "#7bd0ff",
        "surface-dim": "#0f1419",
        "primary-fixed-dim": "#91db2a",
        "on-tertiary-fixed": "#001e2c",
        "inverse-surface": "#dee3ea",
        "error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "1rem",
        gutter: "1.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "margin-desktop": "3rem",
        "space-2xs": "0.25rem",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "space-xl": "2rem",
      },
      maxWidth: {
        "max-width-content": "1280px",
      },
      fontFamily: {
        "headline-sm": ["Outfit"],
        "display-hero": ["Outfit"],
        "body-sm": ["Inter"],
        "stat-metric-mobile": ["Outfit"],
        "headline-md": ["Outfit"],
        "headline-lg": ["Outfit"],
        caption: ["Inter"],
        "body-md": ["Inter"],
        "display-hero-mobile": ["Outfit"],
        "body-lg": ["Inter"],
        "stat-metric": ["Outfit"],
        "badge-label": ["Outfit"],
        "button-text": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
      },
      fontSize: {
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "stat-metric-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        caption: ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "stat-metric": ["44px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "badge-label": ["12px", { lineHeight: "16px", letterSpacing: "0.12em", fontWeight: "700" }],
        "button-text": ["14px", { lineHeight: "20px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
